robo: #namespace

    n_actions: 2
    #environment variables
    min_pole_angle: -0.2 #-23°
    max_pole_angle: 0.2 #23°
    
    max_base_velocity: 1000
    max_base_pose_x: 180
    min_base_pose_x: -180
    
    # those parameters are very important. They are affecting the learning experience
    # They indicate how fast the control can be
    # If the running step is too large, then there will be a long time between 2 ctrl commans
    # If the pos_step is too large, then the changes in position will be very abrupt
    running_step: 0.001 # amount of time the control will be executed
    pos_step: 0.002 # increment in position for each command
    
    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.9
    epsilon_discount: 0.999
    nepisodes: 2000
    nsteps: 1000
    number_splits: 5 #set to change the number of state splits for the continuous problem and also the number of env_variable splits

    init_pos: 0.0 # Position in which the base will start
    wait_time: 0.1 # Time to wait in the reset phases
    
